### ISSUE TITLE
Vue 3 Support [Discussion]

### ISSUE THREAD

**Issue by mits87** [vue-stripe/vue-stripe#148]
Hi, 

Right now looks like the plugin doesn't work with Vue3. 
When I'm trying to use it I've got an error:

<img width="514" alt="Screenshot 2020-10-28 at 11 17 04" src="https://user-images.githubusercontent.com/605186/97423302-50754a80-190f-11eb-95a3-a56b3315fe68.png">

Can you add Vue3 support ?

**Comment by jofftiquez** [comment]
Hello @mits87 yes, support for Vue3 is something that I am considering in the near future. However there are no solid plans yet. I will pin this issue to serve as a discussion section. Thank you!

**Comment by dodanex** [comment]
hello @jofftiquez , any updates on Vue 3 support with composition api? thanks

**Comment by jofftiquez** [comment]
Hello @dodanex the status is the same. I am currently focusing on some major update. After that (end of the year) I will be able to create a timeline for this. Thanks.

**Comment by MCYouks** [comment]
Hi @jofftiquez 👋 Any update on the timeline ? Thanks

**Comment by jofftiquez** [comment]
Hello @MCYouks thank you for asking. So far there's no significant progress yet, I've been busy finalizing the documentations these past few weeks. Hopefully I can continue working on it soon. Will keep you guys posted.

**Comment by toshkoevo** [comment]
Trying to use the library with Ionic Vue and unfortunately I get:
```
Uncaught (in promise) TypeError: selfHook.bind is not a function
    at callSyncHook (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6057)
    at applyOptions (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5811)
    at finishComponentSetup (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6672)
    at setupStatefulComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6603)
    at setupComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6543)
    at mountComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4253)
    at processComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4229)
    at patch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:3856)
    at mountChildren (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4029)
    at processFragment (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4189)
```

Ionic uses Vue3

**Comment by jofftiquez** [comment]
Update: 

I am currently (slowly) getting started with familiarizing Vue 3 now. I still don't know that the side effects would be so I still can't create a checklist of todos. Just want to let you know guys that this is slowly but surely moving. Stay safe everyone! ❤️

**Comment by thinknirmal** [comment]
Hi @jofftiquez, any update on this Vue 3 support? Considering this project is now a Stripe-funded Verified Partner, people would be trusting it too much. Thanks!

**Comment by jofftiquez** [comment]
@thinknirmal thank you for checking in again. You are right, I'll see what I can do to prioritize this. No promises tho. Regardless I will continue what I have already started. I will keep you guys posted here. Thanks.

**Comment by Lord-Y** [comment]
Can't wait to try the Vue 3 versions

**Comment by Sirius-al** [comment]
Is this Fixed Yet for Vue 3.

**Comment by semanticmx** [comment]
> Is this Fixed Yet for Vue 3.
@Sirius-al 
You can checkout PR #221 branch and help us test Vue 3 support there. This fix has not been merged yet so the main master branch still has not support for Vue 3.

**Comment by Lord-Y** [comment]
@jofftiquez Any updates on the refactoring to support Vue 3?

**Comment by jofftiquez** [comment]
Hello everyone, first of all, I would like to sincerely apologize to all of you for the delays to the vue 3 version. It has been a tough few months for me, and I am having a hard time balancing my projects. But, I don't want this to be an excuse not to honor my commitments to this project. Please have a little more patients with me as I will surely deliver this as soon as I can. Stay safe everyone and happy coding. Thank you for understanding.

**Comment by seand88** [comment]
thanks for the update, looking forward to the vue3 version

**Comment by tomparle** [comment]
All the best @jofftiquez for your work on Vue 3 support, I know it may be tough to make some progress on several projects at the same time.
Thanks again for your work, don't hesitate to call for help for testing, docs or anything we could do.

**Comment by YosefOberlander** [comment]
Hello,

Any update in support for vue3?

**Comment by MCYouks** [comment]
Hello @jofftiquez , thanks for your work. Looking forward to seeing Vue 3 support for this project 😄

**Comment by GijsGoudzwaard** [comment]
@jofftiquez Is there anything we can do to help in getting vue-stripe ready for vue 3? As I understand https://github.com/vue-stripe/vue-stripe/pull/221 is a semi working version for vue 3. Maybe it's an idea to put that in a separate branch so that people can start implementing vue stripe with vue 3?

**Comment by jofftiquez** [comment]
Hello everyone, apologies for the long wait. 2021 has been really hard for me and I really appreciate your understanding and being patient. I couldn't wish for a better community than I have with you guys. With regards to this, I am officially starting the upgrade for Vue 3 this year. A lot is in store for Vue Stripe in 2022. I am also talking to some incoming major contributors from the organization I started here in the Philippines (see https://ossph.org). 

Kindly check [this project](https://github.com/orgs/vue-stripe/projects/1/views/1), and let me know if you guys have anything in mind that we can add.

2022 is starting not very well for some of us because of Omicron, but I hope that we can still get by with the proper mindset and with the support from other people we love. Stay safe, everyone! <3

**Comment by tomparle** [comment]
Thank you for the news @jofftiquez !
I hope you to stay safe and well too.

For information, the url you provided to check your project (https://github.com/orgs/vue-stripe/projects/1/views/1) seems broken (at least for me), would you have another one ?

**Comment by jofftiquez** [comment]
@tomparle thank you!

Hmm it seems the "projects [beta]" is not public. But here it is:

![Screenshot_20220111_082917](https://user-images.githubusercontent.com/8638243/148860513-351d7dd0-ae3b-4b37-a981-0c321ab2d5cc.png)

It's just the major summary of all of the things for vue 3. This will come after some major updates for Elements for the current version.

**Comment by tomparle** [comment]
That sounds great, thanks !
Note that TypeScript is not mandatory to use Vue 3, although it's of course a good thing to familiarize with it and benefit of this language's features for writing Vue code !

**Comment by jofftiquez** [comment]
> That sounds great, thanks !
Note that TypeScript is not mandatory to use Vue 3, although it's of course a good thing to familiarize with it and benefit of this language's features for writing Vue code !

Certainly, @tomparle. This is just for personal benefits, it will help the onboarding to the project a lot easier and safer. Also, Stripe uses TypeScript internally, it would be a nice touch to align with them. But, point taken. Thank you.

**Comment by tomparle** [comment]
I agree with what you said and would have done the same if I were you !

**Comment by tomaszukovskij** [comment]
Hi @jofftiquez Thank you for creating stripe for vue. I am using latest version 4.4.1, importing `stripe-checkout` but on page leave I am receiving weird error 
My stripe config: 
`<stripe-checkout
        ref="checkoutRef"
        mode="payment"
        :pk="pk"
        :line-items="lineItems"
        :success-url="successURL"
        :cancel-url="cancelURL"
        :billingAddressCollection="'required'"
      />`

Thank you! <3 
![image](https://user-images.githubusercontent.com/25223364/151759180-9d554c99-3d0b-4764-96f3-ee36d273cb17.png)

**Comment by jofftiquez** [comment]
Hi all, I am currently playing with vue 3 and I made a couple of re-iteration on how I will approach the transition. Upon a few times of trying to make vue 2 and 3 co-exist in one setup, I decided to just override everything and re-write (which will probably be the case anyway) the whole thing in typescript. I am still unsure how to maintain the current version after this so I am still doing additional research for the setup. 

That's all, I just want to update everyone about the progress. Thank you for you patience.

**Comment by nilsm** [comment]
In the meantime it would be good to have a clear message on the homepage to say that it's not Vue 3 compatible yet. Having the 'Vue 2 Version' link on there made me think that the current version is aimed at Vue 3.

As a workaround, if you're using Stripe Checkout with server-side integration, it's very easy to code by using the `@stripe/stripe-js` npm package instead of vue-stripe. Here is a snippet:

`npm install @stripe/stripe-js`

```
<template>
  <div>
      <button @click="pay">Pay</button>
  </div>
</template>
<script>
    import {loadStripe} from '@stripe/stripe-js';
    import axios from "axios"; // use your own server-side library here
    export default {
    methods: {
        async pay() {
            try {
                // your server-side script to get a sessionId - you'll need to customise this
                const res = await axios.post("/api/getSessionId");
                const sessionId = res.data?.sessionId; // customise to get your sessionId value from the result

                // load stripe
                const stripe = await loadStripe('<-- your publishable key -->');
                stripe.redirectToCheckout({ sessionId })
            } catch(err) {
                console.error(err);
            }
        }
    }
    };
</script>
```

**Comment by jofftiquez** [comment]
Good day everyone, sorry to say that I will be cancelling the typescript version. It is taking me a lot of time to implement. I will now use JS for vue 3, also to provide better backwards compatibility with vue 2 version. Apologies for the extra delays. 😥

**Comment by brunokunace** [comment]
@jofftiquez have a public repo for us help you? or a private =)

**Comment by fbmfbm** [comment]
Hi, any news about this ?
Need to use it in vue 3 prod.

Thank's a lot for your work !

**Comment by tomparle** [comment]
@fbmfbm , as much as I support this plugin and the author, I may suggest you to use directly Stripe.js instead. You will have one less dependency, no problem with vue 3, and the migration is very easy.

**Comment by fbmfbm** [comment]
@tomparle
Yes,thank...that's the way for now in prod !

**Comment by jofftiquez** [comment]
> @fbmfbm , as much as I support this plugin and the author, I may suggest you to use directly Stripe.js instead. You will have one less dependency, no problem with vue 3, and the migration is very easy.

Thank you for this @tomparle. I agree with Tom, if you really absolutely need the integration as soon as possible, I'd suggest go with this route. 

@everyone, The development for the vue 3 version is now ongoing but I am still in the tooling part, this may slow me down a bit more (almost done) because I want to be critical with how everything is set up specially, given the amount of time that I am giving to this project, I might not be available to fix bugs immediately that's why I am setting up everything I can to prevent this in the future. In any case, I was able to mange to make the implementation I have in mind work in my local project. There is an existing branch already but I chose not to share it for now because of how bare it is (and for some personal reasons) and how it can change a lot in the coming days. But for transparency's sake I can share a screenshot of the project changes in the past few days.

![image](https://user-images.githubusercontent.com/8638243/162679857-c67874b4-ab26-42be-aa56-ee586339ab31.png)

I have no excuse for the delays because this is a public work I chose to take on, but I am always thankful for your understanding and support. Please bear with me for a little longer.

I created this Twitter Community thing so I can update you there with the updates. Please don't hesitate to join 👉🏽 https://twitter.com/i/communities/1506778375733403648

**Comment by codegeek1001** [comment]
Hi jofftiquez, Thank you for your hard work so far. Have you made more progress on this ? I am looking to use this awesome library with Vue 3 soon. If there is no ETA yet, no worries and I will use Stripe.js directly but wanted to double check.

**Comment by hilal-hipster** [comment]
@jofftiquez 
Any updates?

**Comment by james090500** [comment]
Hi everyone,

I am testing some initial Vue3 support for Vue-Stripe, see PR here! 

https://github.com/vue-stripe/vue-stripe/pull/308

Please submit any PR's to my branch so we can try stabilise things!

**Comment by illegalnumbers** [comment]
Hi @jofftiquez, are there any updates here?

**Comment by jofftiquez** [comment]
Hello @everyone, how are you? Happy new year and I hope you all are doing good, whatever you guys are up to. 2022 has been really hard for me, I know I said it already but these past months has really been tough. I had so many challenges, personal, and career-wise. Despite all, I managed to get back and I am planning to be more present in the coming days/weeks/months. I want to apologize for the long delay and I also want to thank you for still sticking around and supporting this community. With that I want to let you guys know that version 5 has continued and it has changed a lot since I first created it. You can check the development progress in [this branch](https://github.com/vue-stripe/vue-stripe/tree/refactor/v5). 

If you have any questions or suggestion, please add them to this thread. Thank you!

**Comment by codegeek1001** [comment]
Thanks @jofftiquez . First, no worries. I know how hard it is to manage OSS work. Your work is appreciated. Excited to see progress on this.

**Comment by jofftiquez** [comment]
> Thanks @jofftiquez . First, no worries. I know how hard it is to manage OSS work. Your work is appreciated. Excited to see progress on this.

Thank you so much!

**Comment by jofftiquez** [comment]
Hello @everyone please check the macro progress here: https://github.com/orgs/vue-stripe/projects/2

**Comment by jofftiquez** [comment]
More updates here: https://github.com/vue-stripe/vue-stripe/tree/refactor/v5#development-logs

- Checkout is now working
- Initialization of Stripe instance via composable-like approach done
- Initialization of Elements instance via composable-like approach done
Up next:
- Payment Element composable and component

Feel free to check the codes and give feedback. Thanks

**Comment by jofftiquez** [comment]
Hello everyone, new updates here https://github.com/vue-stripe/vue-stripe/pull/317 

We'll be releasing the version 5 soon. Thank you all for your understanding.

**Comment by gustavosbarreto** [comment]
Any update on this?

**Comment by jofftiquez** [comment]
I didn't realize the projects page is not public so I made it public and updated the progress for some of the tasks here https://github.com/orgs/vue-stripe/projects/2

It's been really slow on my end for this past few months, and I know you guys are tired of hearing apologies but I'm gonna apologize again anyway for the delays. This is 101% on me, my personal issues shouldn't be your problem, guys. But I also wanna thank you all for being patient despite the delays. No more excuses, I will do what I have to do no matter what. Thank you again. 

P.S. This is a one-man team effort that's why even if I work on the tasks it really may take a while. All kinds of help are welcome. 🙏

**Comment by jofftiquez** [comment]
Updates:

Check the summary here: https://twitter.com/jrtiquez/status/1686811628699017216

Answer the poll for community improvement: https://twitter.com/jrtiquez/status/1686812250190082049

If you can't see the link, you're probably not joined in the twitter community yet. Please join here: https://twitter.com/i/communities/1506778375733403648

Thank you @everyone!

**Comment by dapug** [comment]
Will you be publishing to NPM before the docs and samples are ready?

**Comment by asivaneswaran** [comment]
@jofftiquez Hey, any news on if we can get a preview-branch or a beta branch so we can start working on it while the docs and guides are being built?

**Comment by bpospanov** [comment]
> @jofftiquez Hey, any news on if we can get a preview-branch or a beta branch so we can start working on it while the docs and guides are being built?

There is a v5 branch, I guess you can check it out

**Comment by klepfish** [comment]
Any ETA on when this version might be ready to start testing out?

**Comment by asivaneswaran** [comment]
Is this package still supported and maintained?

**Comment by dapug** [comment]
> Is this package still supported and maintained?

I'm gonna chalk it up as a hard no.  Vue 3 inquiry OPEN for 3 solid years... 

**Work-around:**
I loaded Stripe's own active and well-supported **@stripe/stripe-js** library and used it directly.  Most the time it took for me to figure this out was not JS or Vue, it was making sure I understood Stripe itself, how it works, docs, and samples.  In my case, I needed to add a recurring subscription to a service, and wanted to use stripe elements.  So that means understanding "Payment Intent" and digging through some samples:

https://stripe.com/docs/billing/subscriptions/build-subscriptions?ui=elements
https://stripe.com/docs/js
https://github.com/stripe-samples/checkout-single-subscription/blob/main/client/index.html

Then in your component (example using TS):

```ts
import { loadStripe, Stripe } from "@stripe/stripe-js"

setup() {

   const stripe = ref()
   const elements = ref()

   onMounted(){

      const publishableKey = "pk_test_...YOUR_KEY"
      stripe.value = await loadStripe(publishableKey)

      // get client secret from your back end (see Stripe docs)
      const { clientSecret, error: backendError } = await fetch("/api/Payments/PaymentIntent").then((res) => res.json())

      const appearance = { /* appearance */ }
      const options = { /* options */ }
      elements.value = stripe.value.elements({clientSecret, appearance})
      const paymentElement = elements.value.create('payment', options)

      paymentElement.mount("#payment-element")
   }

    const handleSubmit = async () => {
      const { error } = await stripe.value.confirmPayment({
        elements: elements.value,
        confirmParams: {
          return_url: `${window.location.origin}/success`
        }
      });

      if (error.type === "card_error" || error.type === "validation_error") {
        console.log(error.message)
      } else {
        console.log("An unexpected error occured.")
      }
    }
}
```
And then your template simply has an element that stripe can attach to (`id="payment-element" `), and a button call:

```html
<template>
    <main>
      <form id="payment-form" @submit.prevent="handleSubmit">
        <div id="payment-element" />
        <button id="submit">Subscribe</button>
      </form>
    </main>
  </template>
```

**Comment by WayneBuckhanan** [comment]
> I really would like to have something similar to the doc sample working inside a Vue3 application. If someone has a sample to share, it would be great 🙏

Here's a sanitized gist of a test spike I made over the summer.
  https://gist.github.com/WayneBuckhanan/5dcacb5dee7df478c959682d7e4d8d74
Independent of it using AWS Amplify with a Lambda as the backend, you should be able to see how to use the Stripe library directly for a Checkout session in Vue3. If that's all you're doing, you may not need vue-stripe at the moment.

HTH

**Comment by jofftiquez** [comment]
Closing this to move the discussion here https://github.com/vue-stripe/vue-stripe/discussions/236 

This issue is still referenced to the new discussion so we won't lose the history. Thanks all!
