### ISSUE TITLE
stripe-element-card won't render [No internet]

### ISSUE THREAD

**Issue by muarachmann** [vue-stripe/vue-stripe#191]
**Describe the bug**
Stripe element card doesn't mount when not connected to the internet and doesn't seem to trigger the error callback

**To Reproduce**
Insert a stripe card element

```
<stripe-element-card
        @error="stripeError"
        ref="stripeCard"
        :pk="stripePublishableKey"
  />

...
...
...

methods: {
     stripeError(error) {
         console.log(error)
    }
}
```
..

**Expected behavior**

Throw error with a callback to handle appropriately.

**Screenshots**
As you can see the card renders properly when connected to the internet but doesn't when not connected to the internet.
Is this the expected behavior.... I noticed this when testing 
<img width="446" alt="Screen Shot 2021-04-23 at 3 40 16 PM" src="https://user-images.githubusercontent.com/16350814/115888003-5d03d700-a44a-11eb-9192-d9227b177e69.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browsers: chrome, safari

**Additional context**
As per the docs https://vuestripe.com/stripe-elements/card in the events section. I was hoping the error will be triggered and I could handle it and display some message or so.

**Comment by jofftiquez** [comment]
Hello @muarachmann this is expected behavior. The script that loads the stripe elements is being fetched from Stripe's CDN link. It's only natural to fail when there's no internet. 

Maybe you should handle the connection error on the application level and not on the component level. This way you could show a message to the user before the loading of any other components. 

If I'm not mistaken, the only error thrown from Stripe's error callback is the actual error coming from their server. For example, if there's an invalid payload.

**Comment by muarachmann** [comment]
@jofftiquez you are right the `@error` and thanks for your response triggers when the form is submitted. Feel free to close this and thanks for this amazing package can't wait to see future updates :D

**Comment by jofftiquez** [comment]
Thank you for using it! There will be more cool stuff in the future. 💪👌
