### ISSUE TITLE
Error 'window is not defined' when refreshing the page

### ISSUE THREAD

**Issue by jesephan** [vue-stripe/vue-stripe#211]
**Describe the bug**
When stripe-checkout component is rendered inside a wizard form and user reload the page it will show **Window is not defined** you can check the attach image for more details. Fyi i already set { src: '~/plugins/vue-stripe.ts', ssr: false }

**To Reproduce**
Im using Nuxt @ v2.14.12 and I integrate this page/component inside a wizard form. 

**Expected behavior**
It should just load the page w/o any issue.

**Screenshots**
Here is the [screenshot](https://drive.google.com/file/d/1BK7ZbxKWA4HxHWJlQARNw9JPJQzULhNx/view?usp=sharing)

**Desktop (please complete the following information):**
 - OS: [e.g. OSX]
 - Browser [chrome]
 - Version [91.0.4472.114]

**Additional context**

**Comment by jofftiquez** [comment]
Hello, may I know what version of `vue-stripe` are you using? And perhaps a snippet of your implementation. Thanks.

**Comment by jesephan** [comment]
@jofftiquez my package version is set to `"@vue-stripe/vue-stripe": "^4.2.5"` here is the [link](https://pastebin.com/QehmG1zA) of my implementation

**Comment by hansemannn** [comment]
It seems to be an issue with SSR / server-side-rendering that is not handled in the Stripe integration, is that possible?

**Comment by jofftiquez** [comment]
@hansemannn you are right, although the importing of Stripe.js should solve this issue, that's why I'm a bit confused. Anyway, I will check @jesephan's implementation to see what's up.

**Comment by jofftiquez** [comment]
@jesephan you can omit this part in your implementation. 

`import { StripeCheckout } from '@vue-stripe/vue-stripe';`

Did you do [this part](https://github.com/vue-stripe/vue-stripe-checkout-nuxt-demo/blob/master/README.md#step-3)? 

As you can see, importing the component directly to the consuming component is not present in [this sample](https://github.com/vue-stripe/vue-stripe-checkout-nuxt-demo/blob/master/README.md#usage).

Handling SSR is a bit different compared to regular SPA that's why we need to do these approaches to make it work.

**Comment by jesephan** [comment]
@jofftiquez @hansemannn seems to be removing the import and instead rely on the auto import solves my problem. 
so to anyone having this issue, removing `import { StripeCheckout } from '@vue-stripe/vue-stripe';` from your component will solve it.

Thank you so much guys.
